### ISSUE TITLE
Discretization Method

### ISSUE THREAD

**Issue by makeller1** [nicolapiccinelli/libmpc#10]
I think it would be useful to inform what method is used for discretization. Looks like zero-order-hold. Would like to see that stated in the docs.

**Comment by nicolapiccinelli** [comment]
Hello, @makeller1 to what discretization method are referring to? There are few routines used both in linear and nonlinear MPC.

Are you encountering issues due to the discretization of the system model or to the automatic gradient estimation? If so, it would be useful to describe better your use case.

Cheers!

**Comment by makeller1** [comment]
Ideally a discretization method would be attributed to each routine. I do not know of any issues related to it, just that the discretization method informs design decisions around step size.

**Comment by nicolapiccinelli** [comment]
In the linear mpc, the discretization is up to the user, there's just a util routine to compute the zoh. For the nonlinear case currently, if the user provides a continuous time system the solver internally converts it using zoh. Anyhow, even in this case, you can implement the discretization routine you prefer by directly providing the discrete system model.

I will put a note of that in the docs.

**Comment by makeller1** [comment]
Great, thank you!
