### ISSUE TITLE
Custom numerical integrator for MPC predictions

### ISSUE THREAD

**Issue by sara9915** [nicolapiccinelli/libmpc#36]
Hello @nicolapiccinelli, I'd like to use your library, but I need to employ a custom numerical integrator to make the MPC predictions along the prediction horizon. Can you give me some info about the routine now used to do this? I see there is an RK4 class, but I didn't find anywhere its usage in the provided examples.

**Comment by nicolapiccinelli** [comment]
Hello, @sara9915. Are you referring to the integration of the model dynamics?

**Comment by sara9915** [comment]
Yes, exactly

**Comment by nicolapiccinelli** [comment]
Ok, the library is handling things differently between linear and non-linear MPC. Which one are you interested in?

**Comment by sara9915** [comment]
Non-linear MPC

**Comment by nicolapiccinelli** [comment]
If you already have a discrete-time model, the library is simply propagating the state x(k+1) = f(x(k),u(k)). Otherwise, if you provide a continuous time model, the integration is performed using the sample time's central difference.  In this case, the integration exploits the prediction horizon to implement the integration scheme.

**Comment by sara9915** [comment]
I got it, thank you!
